print("===============================================================================")
print("=============================Login=============================================")
print("===============================================================================")
print("===============================================================================")
username = input("Enter your Username:")
print("===============================================================================")
password = input("Enter your password:")
if username == 'Medina1234' and "newbie290" == password:
    print("===============================================================================")
    print("=========================Welcome User Medina1234===============================")
    print("===============================================================================")
    print("==================================Home=========================================")
    print("===============================================================================")
    print("==========================Select a option to proceed===========================")
    print("===============================================================================")
    print("1.Upload Files")
    print("2.How to use?")
    print("3. Quit")
    select = int(input("Enter a number\n"))
    if select == 1:
        print("===============================================================================")
        print("========================File Section===========================================")
        print("===============================================================================")
        print("====================Select a Filetype to upload================================")
        print("===============================================================================")
        print("1.MP4, mkv, mov & other video format")
        print("2.Docx, PPTs and other microsoft file")
        print("3.Zip, Rar or etc")
        select2 = int(input("Enter a number\n"))
        if select2 == 1:
            filetype1 = input("Enter the file name Example: example.mov or Mp4")
            print("uploading!!")
            print("10%==")
            print("20%====")
            print("30%======")
            print("40%========")
            print("50%==========")
            print("60%===========")
            print("70%=============")
            print("80%===============")
            print("90%=================")
            print("100%===================")
            print("The filename" + filetype1, "Has successfully Uploaded")
        elif select2 == 2:
            filetype2 = input("Enter the file name like Zip, Rar or etc")
            print("uploading!!")
            print("10%==")
            print("20%====")
            print("30%======")
            print("40%========")
            print("50%==========")
            print("60%===========")
            print("70%=============")
            print("80%===============")
            print("90%=================")
            print("100%===================")
            print("The filename" + filetype2, "Has successfully Uploaded")
        elif select2 == 3:
            filetype2 = input("Enter the file name like Docx, PPTs and other microsoft file")
            print("uploading!!")
            print("10%==")
            print("20%====")
            print("30%======")
            print("40%========")
            print("50%==========")
            print("60%===========")
            print("70%=============")
            print("80%===============")
            print("90%=================")
            print("100%===================")
            print("The filename" + filetype2, "Has successfully Uploaded")
        else:
            print("Error select the following category")

    elif select == 2:
        print("===============================================================================")
        print("=========================How to use it?========================================")
        print("===============================================================================")
        print("1.Select the Upload a file")
        print("Select a filetype")
        print("Enter the Filename and Done")
    elif select == 3:
        print("Exit??")
    else:
        print("Select from the category")
else:
        print("try again")
